### ISSUE TITLE
No execution started when the WPS ID is more than 42 characters

### ISSUE THREAD

**Issue by JannesLathouwers** [EOEPCA/proc-ades#10]
When trying to start an execution for an application where the WPS ID (`<workflow_id>_<s:softwareVersion>` is longer than 42 characters, nothing happens. Deploying the process is fine, but when the execute request is sent, nothing happens. No Calrissian pods are created, no error is shown in the ADES logs.

k8s version: `1.22.5`
ADES: `1.1.2`

**Comment by rconway** [comment]
Waiting for input from @bbrauzzi

**Comment by bbrauzzi** [comment]
Hi @JannesLathouwers 
I am sorry but I was not able to reproduce the issue. Could you please provide more details of your job submission?
Note that the process id (<workflow_id>_<s:softwareVersion>) differs from the job namespace name in k8s.

**Comment by JannesLathouwers** [comment]
Hi @bbrauzzi, sorry for the late reply.
The issue occurred for me when providing a CWL with the following values:
```yaml
#!/usr/bin/env cwl-runner
$graph: 
- class: Workflow
  id: this_identifier_is_too_long_for_some_reason  # <-- this seems to be an issue
...
- class: CommandLineTool
  baseCommand: python3
...

cwlVersion: v1.0

$namespaces:
  s: https://schema.org/
s:softwareVersion: 3.0.7
. . . .
```
The ADES concatenates the `id` and the `s:softwareVersion` into the identifier. When this result is more than 42 characters, the ADES fails silently for me. I also tried with a shorter `id` but a longer `s:softwareVersion` (while the total length is still over 42 characters). This also fails. 

When this identifier generated by the ADES is shorter than 42 characters it works as expected.
